get_all_instance_state:
  stage: deploy
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/amazon/aws-cli:2.23.6
    entrypoint: [""]
  script:
    - ./scripts/get_all_instance_state.sh
  when: manual
