---
- hosts: all
  gather_facts: false
  strategy: free
  #become: yes
  #pipelining: true
  tasks:
    - ansible.builtin.apt:
        name: tailscale
        state: latest
        update_cache: yes
    - ansible.builtin.copy:
        src: files/50-tailscale
        dest: /etc/networkd-dispatcher/routable.d/50-tailscale
        mode: '0755'
    - ansible.builtin.shell: /etc/networkd-dispatcher/routable.d/50-tailscale

    - ansible.builtin.shell: /usr/bin/tailscale set --auto-update
    - ansible.builtin.shell: /usr/bin/tailscale set --advertise-exit-node
